### ISSUE TITLE
qmake -spec macx-g++ not working with Qt 5.10.1 (from Homebrew)

### ISSUE THREAD

**Issue by maelvls** [tsuna/autotroll#1]
Hi,
This line seems to break the build using Qt 5.10.1 and clang-900.0.39.2:
https://github.com/tsuna/autotroll/blob/079aebf28f4b543f178f869b642b9cb606cbdac4/build-aux/autotroll.m4#L200

When running the command `./configure --with-qt=/usr/local/opt/qt/bin`:
```
...
checking for moc... /usr/local/opt/qt/bin/moc
checking for uic... /usr/local/opt/qt/bin/uic
checking for rcc... /usr/local/opt/qt/bin/rcc
checking whether host operating system is Darwin... yes
Project ERROR: failed to parse default search paths from compiler output
```

The error occurs when running `qmake -spec macx-g++` from inside the contest.dir folder.

I tried using `qmake -spec macx-clang` instead and it seemed to work. What do you think causes that error?

Thanks for your excellent work on Autotroll!!!

**Comment by maelvls** [comment]
Apparently, macports uses `macx-clang` when using qt5 ([code](https://github.com/macports/macports-ports/blob/5e4c2fb8e365e73c5ec070c027de4d1050cd7740/graphics/ttfautohint/Portfile#L44), see [related issue](https://trac.macports.org/ticket/55365?cversion=0&cnum_hist=7)):
```
    post-extract {
        reinplace  "s/at_qmake_args='-spec macx-g++'/at_qmake_args='-spec ${qt_qmake_spec}'/" configure
    }
```

where `qt_qmake_spec ` is set to
- `macx-g++` when using qt4 ([code](https://github.com/macports/macports-ports/blob/7575a87046cc21e4530406e15c77c4379b9a458b/_resources/port1.0/group/qt4-1.0.tcl#L152))
- `macx-clang` when using qt5 ([code](https://github.com/macports/macports-ports/blob/7575a87046cc21e4530406e15c77c4379b9a458b/_resources/port1.0/group/qt5-1.0.tcl#L611))

The line

https://github.com/tsuna/autotroll/blob/079aebf28f4b543f178f869b642b9cb606cbdac4/build-aux/autotroll.m4#L200

will probably only work with qt4. How could we fix that?

**Comment by lemzwerg** [comment]
What about making `autotroll.m4` honour the [`QMAKESPEC`](http://doc.qt.io/qt-5/qmake-running.html#makefile-mode-options) environment variable?  If set, autotroll wouldn't add a `-spec` argument by its own.

**Comment by lemzwerg** [comment]
I've implemented this now.  Please check!

**Comment by maelvls** [comment]
Thanks so much! Excellent work.

You did well to explicitely output the QMAKESPEC so that ppl see it during configure 👍
